language: go

go:
  - 1.7
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/pierrre/gotestcover
  - go get golang.org/x/tools/cmd/cover

install:
  - go get github.com/stretchr/testify/assert

script:
  - $HOME/gopath/bin/gotestcover -coverprofile=cover.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci